### ISSUE TITLE
Websocket support (django channels)

### ISSUE THREAD

**Issue by cisarik** [behave/behave-django#16] opened 2016-07-15 09:48 UTC
Is it possible to configure behave-django to test django apps with [channels](http://channels.readthedocs.io) integrated?

For WSGI there is wsgiref used right in the documentation:

``` python
import threading
from wsgiref import simple_server
from selenium import webdriver
from my_application import model
from my_application import web_app

def before_all(context):
    context.server = simple_server.WSGIServer(('', 8000))
    context.server.set_app(web_app.main(environment='test’))
    context.thread = threading.Thread(target=context.server.serve_forever) context.thread.start()
    context.browser = webdriver.Chrome() 
```

However Django channels is using ASGI and daphne: [http://channels.readthedocs.io/en/latest/asgi.html](http://channels.readthedocs.io/en/latest/asgi.html)

Currently I’m deploying my app (for debugging) by:

``` bash
$ venv/bin/daphne <app>.asgi:channel_layer --port 80 --bind 0.0.0.0 -v2
$ venv/bin/python manage.py runworker --settings=<app>.settings -v2
```

How can I configure behave-django to use daphne (and use runworker..) 

I tried to set "context.server" in "before_all", googled a lot but I still can't figure it out. 

Should I override DjangoBehaveTestSuiteRunner and if so, how?

**Comment by isparks** [comment] 2017-01-20 16:35
I have also struggled with this. In essence you need to set up some channel backend, test database, start daphne (ASGI) server and some workers, run the behave tests and then tear everything down afterwards.

I looked into the channels runserver command and with what I learned from that created this behave example (not behave-django but hopefully it will be a useful basis/discussion point). This works for me with:

```bash
$ behave
```

```python
# -*- coding: utf-8 -*-
# environment.py for behave and Django with Channels...
import os
import sys
import django
import threading
from copy import copy
from splinter import Browser
from django.conf import settings
from django.test.runner import DiscoverRunner
from django.core.management import call_command
from daphne.server import Server, build_endpoint_description_strings
from channels import DEFAULT_CHANNEL_LAYER, channel_layers
from channels.staticfiles import StaticFilesConsumer
from channels.worker import Worker

# Setup the environment for standalone
pth = os.path.dirname(os.path.abspath(__file__))
sys.path.append(pth)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myapp.settings")
django.setup()


TEST_HOST = '192.168.1.179'  # You'll probably be 127.0.0.1
TEST_PORT = 5000 # Whatever you like, trying to avoid a clash with dev server on 8000
TEST_CHANNEL_LAYER = 'TEST_CHANNEL_LAYER'

# Using a copy of default. WARNING: if devserver is running will clash with its use of the same backend
test_channel_config = copy(settings.CHANNEL_LAYERS[DEFAULT_CHANNEL_LAYER])
# Changes to the config here...
# Set up our own channel layer using a copy of the default one so we don't name clash with any running devserver
settings.CHANNEL_LAYERS[TEST_CHANNEL_LAYER] = test_channel_config


class WorkerThread(threading.Thread):
    """
    Class that runs a channel worker
    """
    def __init__(self, channel_layer):
        super(WorkerThread, self).__init__()
        self.channel_layer = channel_layer

    def run(self):
        worker = Worker(channel_layer=self.channel_layer, signal_handlers=False)
        worker.ready()
        worker.run()


def after_scenario(context, scenario):
    """
   Clear after every scenario 
    """
    call_command('flush', interactive=False, verbosity=0)

def before_all(context):

    # Use a runner to setup and teardown database instances for us
    context.runner = DiscoverRunner()
    context.runner.setup_test_environment()
    context.old_config = old_config = context.runner.setup_databases()

    # Set up a named channel for our workers to listen on and have them serve static files also
    channel_layer = channel_layers[TEST_CHANNEL_LAYER]
    channel_layer.router.check_default(http_consumer = StaticFilesConsumer())

    # Fire off some workers 
    for _ in range(4):
        worker = WorkerThread(channel_layer)
        worker.daemon = True
        worker.start()

    # build the endpoint description string from host/port options
    endpoints = build_endpoint_description_strings(host=TEST_HOST, port=TEST_PORT)

    # Start the daphne server
    context.server = Server(
        channel_layer=channel_layer,
        endpoints=endpoints,
        http_timeout=60,
        verbosity=0
    )

    server_process = threading.Thread(target=context.server.run)
    server_process.daemon = True
    server_process.start()

    # Now the web driver we will need
    context.base_url = 'http://{}:{}'.format(TEST_HOST, TEST_PORT)
    context.browser = Browser('chrome', **executable_path)

def after_all(context):
    # Quit our browser
    context.browser.quit()
    context.browser = None

    # Note: Server and worker threads are daemonized so they die at the end of the script

    # Teardown the test database and environment
    context.runner.teardown_databases(context.old_config)
    context.runner.teardown_test_environment()

```

I hope it helps someone.

**Comment by bittner** [comment] 2017-01-20 17:17
Awesowe, @isparks, to post a working example for integrating channels! Thank you!

A Few Notes
-----------

- The first few lines of `before_all()` look much like the [Manual Integration](https://behave.readthedocs.io/en/latest/django.html#manual-integration) as described in the behave docs. When using the management command, `python manage.py behave`, we should be able to do without that setup, and teardown code in `after_all()`.
- According to the [Channels docs on testing](https://github.com/django/channels/blob/master/docs/testing.rst#testing-consumers) there is a dedicated test case, `ChannelTestCase`. Is that something we could use [as a drop-in replacement](https://github.com/behave/behave-django/blob/master/behave_django/testcase.py#L4) for `LiveServerTestCase` when testing Channels instead of an instance of live-server?

It would be nice to add testing Channels as an additional capability to behave-django with something like:
``` bash
$ python manage.py behave --channels
```
Would that make sense?

**Comment by bittner** [comment] 2017-01-20 18:58
@cisarik and @isparks, can you try to make channels testing work in your projects by adding a few lines to behave-django's code?

1. [behave_django.management.commands.behave:Command:handle()](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L94-L97) -- _add elif-clause:_
``` python
        if options['dry_run'] or options['use_existing_database']:
            django_test_runner = ExistingDatabaseTestRunner()
        elif options['channels']:
            django_test_runner = ChannelBDDTestRunner()
        else:
            django_test_runner = BehaviorDrivenTestRunner()
```
2. [behave_django.management.commands.behave:add_command_arguments()](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L13-L28) -- _append:_
``` python
    parser.add_argument(
        '--channels',
        action='store_true',
        default=False,
        help="Use ChannelTestCase to run tests for your channel layers",
    )
```
3. [behave_django.testcase](https://github.com/behave/behave-django/blob/master/behave_django/testcase.py#L1) -- _add:_
``` python
from channels.tests import ChannelTestCase

class ChannelBDDTestCase(ChannelTestCase):
    def runTest(self):
        pass
```
4. [behave_django.runner](https://github.com/behave/behave-django/blob/master/behave_django/runner.py#L7) -- _add:_
``` python
class ChannelBDDTestRunner(DiscoverRunner, BehaveHooksMixin):
    testcase_class = ChannelBDDTestCase
```
Then, in theory, any BDD tests should run through `ChannelTestCase` when you execute:
``` bash
$ python manage.py behave --channels
```

**Comment by isparks** [comment] 2017-01-20 22:48
@bittner thanks for interest in this. I think ChannelTestCase and LiveServerTestCase are quite different beasts. LiveServerTestCase is doing similar things to my example code above, starting a server, shutting it down etc:

https://github.com/django/django/blob/cecc079168e8669138728d31611ff3a1e7eb3a9f/django/test/testcases.py#L1262

From what I can see of ChannelTestCase and understand from the docs (and I am by no means an expert), it's more for unit testing. Here's a link to code

https://github.com/django/channels/blob/577dfa1eee3e0e1ec23421f33034792023ece050/channels/tests/base.py#L19

Looks like ChannelTestCase allows you to send and receive messages on fake channels but it isn't starting any servers. The pre-channels django LiveServerTestCase starts up django server so it can receive http requests from a browser or another client, ChannelTestCase doesn't create either a http or a websocket endpoint to connect to. In my Django app I request a web page and javascript on that page then opens a websocket connection to the server and I want to test both. But with the code above it might be possible to make a ChannelsLiveServerTestCase which instead of just starting the webserver in a thread which is what liveserver does here:

```python
        cls._live_server_modified_settings.enable()
        cls.server_thread = cls._create_server_thread(connections_override)
        cls.server_thread.daemon = True
        cls.server_thread.start()
```
instead uses code like my example above to start both the Daphne ASGI Server and some channel workers. The same pattern seems possible, although whether starting and stopping Server and Workers for every test case is good for performance I don't know.

**Comment by bittner** [comment] 2017-01-20 23:56
Okay, I see. I'm not a channels user, so I was just trying to make an educated guess.

In this case the best idea would be to write a LiveServerTestCase for channels that starts both the interface servers (Daphne) and the worker servers. Of course, the right place to do this is the Django  project. It shouldn't be too hard to do (you've got the code working already).

**Comment by bittner** [comment] 2017-01-21 07:23
@isparks, I'm a little bit puzzled. The [channel docs](https://channels.readthedocs.io/en/stable/getting-started.html#running-with-channels) say:

> [...] Channels comes with `daphne`, an interface server that can handle both HTTP and WebSockets at the same time, and then ties this in to run when you run `runserver` - you shouldn’t notice any difference from the normal Django `runserver` [...]

... and ...

> (Under the hood, runserver is now running Daphne in one thread and a worker with autoreload in another - it’s basically a miniature version of a deployment, but all in one process)

So, shouldn't it all already work with a regular runserver?

**Comment by isparks** [comment] 2017-01-21 15:28
@bittner yes,  Channels comes with it's own runserver , which overrides the standard django one, and much of my startup code above comes from their runserver command. From here:

https://github.com/django/channels/blob/577dfa1eee3e0e1ec23421f33034792023ece050/channels/management/commands/runserver.py

But what I (and I think @cisarik ) want to achieve is to have behave-django create the test db, start up the ASGI and worker server, run the behave tests and then shut down the server and destroy the test database. At the moment the behave command only creates a standard django server and none of our websocket code will work.

But maybe I miss the point? Sorry to have so much conversation here. I use Channels, have delved in the code of Django, Behave and Channels but I could easily be missing something obvious.

**Comment by bittner** [comment] 2017-01-21 19:24
No worries, I think we're perfectly aligned.

What we want (and need) for your tests with Channels to work is a test case class implementation that fires up an appropriate runserver in addition to preparing and cleaning up a test DB. And in case of Daphne (i.e. Channels) it should "handle both HTTP and WebSockets at the same time" according to the docs ([paragraph 6](https://channels.readthedocs.io/en/stable/getting-started.html#running-with-channels)) already, which would be ideal. (This is actually done, [according to the source code](https://github.com/django/channels/blob/master/channels/management/commands/runserver.py#L37-L38).)

To keep the story short, there needs to be a `ChannelLiveServerTestCase` that roughly runs the code in [Channels' runserver](https://github.com/django/channels/blob/master/channels/management/commands/runserver.py#L18). Somehow the [WSGIServer](https://github.com/django/django/blob/master/django/test/testcases.py#L1252) needs to be replaced in a copy of [LiveServerTestCase](https://github.com/django/django/blob/master/django/test/testcases.py#L1262-L1275), which should probably inherit from [TransactionChannelTestCase](https://github.com/django/channels/blob/master/channels/tests/base.py#L79-L80) in our case. -- Could be that @proofit404 is [trying to come up](https://github.com/django/channels/issues/494#issuecomment-274246224) with something like this.

**Comment by bittner** [comment] 2017-01-23 09:19
FYI, please see https://github.com/django/channels/pull/497 for a WIP PR on `ChannelLiveServerTestCase`.

**Comment by bittner** [comment] 2017-03-23 07:24
Hello all, @proofit404 has contributed a significant amount of work for a `ChannelLiveServerTestCase` in https://github.com/django/channels/pull/497. :1st_place_medal:

**Please** clone the changes, **try the code, and give feedback!** As soon as we have confirmed that this works as needed it's probably going to be merged into django/channel master. Hurry! :rocket: Thank you.

**Comment by bittner** [comment] 2017-04-11 09:58
Django Channels support has now been merged into their master branch. ([ChannelLiveServerTestCase](https://github.com/django/channels/blob/master/channels/test/liveserver.py#L144))

Try It (Now!)
------
Please try if things are working out for you and give feedback, or better: make PRs, right in their repository. Note that @andrewgodwin compiled [a list of TODOs](https://github.com/django/channels/pull/497#issuecomment-293199884) that are meant to be addressed in (near) future.

Add Docs
--------
If someone would make a PR with appropriate instructions for testing channels implementations [in our docs](https://behave-django.readthedocs.io/en/stable/usage.html) then please go ahead - if you see a need for extending our docs. This would be really appreciated!

**Closed by bittner** 2017-04-11 09:58 UTC
Labels: help wanted, question

**Comment by bittner** [comment] 2017-04-11 13:25
Oh, just figured we still need to integrate the [ChannelLiveServerTestCase](https://github.com/django/channels/blob/master/channels/test/liveserver.py#L144) in behave-django conveniently. If anyone would make a PR for this that would be more than awesome!

**Comment by bittner** [comment] 2017-06-22 12:31
Anyone willing to prepare a PR to make the integration of the new functionality complete?

**Comment by UrAvgProgrammer** [comment] 2021-04-22 23:57
@isparks  Thank you for posting a working sample, I am currently encountering the same issue and wanted to do exactly what you wanted to do during that time, would it be possible to ask for the files that you have to dive into for the said packages in order to create your working example? As I was testing it I cant seem to make it work and want to update it myself based on the latest releases... But I don't know where to start to. Thank you!

**Comment by iansparks** [comment] 2021-04-23 08:00
Sorry @UrAvgProgrammer but I haven't looked at Channels since early 2017 when we decided to drop channels and move to a polling solution based on vanilla Django.
