### ISSUE TITLE
'There is 1 other session using the database.'

### ISSUE THREAD

**Issue by Protosac** [behave/behave-django#34] opened 2017-03-24 23:44 UTC
When I run:
`python manage.py behave`

Django begins preparing for tests, but throws this error. `behave-django` appears to be complaining about it's own connection to the database (or Django is complaining about `behave-django`s use of the database). Have any ideas what's going on here?

Python 2.7
Django 1.9.8

Thanks.

**Comment by bittner** [comment] 2017-03-25 08:46
This is probably not related to behave-django as such. You'd have to provide more details, though, ideally steps to reproduce the error.

You may find more helpful hints in similar issues on the web, e.g.

- [Django Test — Unable to drop and recreate test database](http://stackoverflow.com/questions/38999203/django-test-unable-to-drop-and-recreate-test-database) (StackOverflow)
- https://code.djangoproject.com/ticket/22420
- https://github.com/Fantomas42/django-blog-zinnia/issues/476
- [Concurrent Jenkins builds of a Django application](http://blog.richard.do/index.php/2014/09/concurrent-jenkins-builds-of-a-django-application/) (a blog)
- https://github.com/grosser/parallel_tests/issues/412

The last issue suggests that the problem is related to Postgres alone, not even Django. At least the error message comes directly from there. Some other application may use your database while you run the tests.

Please let us know when find the culprit, so others can profit too.

**Comment by bittner** [comment] 2017-04-11 10:00
Closing this issue for lack of activity.

**Comment by dmwyatt** [comment] 2018-12-18 15:14
I decided to look into this issue after just dealing with it for what seems like years.  

What happens is that the tests run fine, but fail to delete the test database because of the other session(s) using database error.  If you run the tests again, django prompts you to delete the test database before continuing.  This is how I've always just dealt with it in the past.

All of my regular Django tests work fine, it is only tests run with behave-django that exhibit this issue.

* Django 2.1.4 
* behave-django 1.1.0
* PostgreSQL 10.1

I'll try and remember to come up with a minimal reproducing project soon.

**Comment by bittner** [comment] 2018-12-18 17:50
That sounds like an interesting background for learning more about the issue. (Thanks for digging!)

Please also mention any other technology that may be involved (e.g. Selenium) and the environment that the failing tests are run in. (I guess, a successfully failing test project to reproduce the issue will exhibit all of that.)

behave-django isn't much "magic", it's mostly just glue code between test tools. I wouldn't be surprised to find a generic issue that can be reproduced without behave-django.

**Comment by nhill-cpi** [comment] 2019-03-13 22:12
@dmwyatt Did you look into this more? Just wondering b/c I'm running into the same error.

**Comment by dmwyatt** [comment] 2019-03-14 16:01
No, I got caught up in another project that doesn't use behave.  Once I get back to a behave-using project I'll be able to investigate.

**Comment by dmwyatt** [comment] 2019-07-25 21:59
I can't remember if this is the solution to the problem I had when I originally commented on this issue, but I came across this issue again in my Googlin' and this time I have a solution to a very similar issue, or maybe even the same issue.

Add `conn_max_age=0` to your database configuration in tests. I figured this out from [this answer](https://stackoverflow.com/a/57090211/23972) on SO.

**Comment by bittner** [comment] 2019-07-27 21:18
Thanks @dmwyatt!

Details to this setting are available from the [Databases section](https://docs.djangoproject.com/en/stable/ref/databases/#persistent-connections) in Django's documentation.

I'm closing this issue as sufficiently discussed.

**Closed by bittner** 2019-07-27 21:18 UTC
Labels: question
