### ISSUE TITLE
django 1.10 compatibility

### ISSUE THREAD

**Issue by lsenta** [behave/behave-django#17] opened 2016-08-11 15:02 UTC
Hi,
I've started using Django, and felt like BDD for my project would be nice.

Is there any plan for a 1.10 compat soon?

with `behave-django` 0.3.0:

```
› python manage.py behave
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/site-packages/behave_django/management/commands/behave.py", line 69, in <module>
    class Command(BaseCommand):
  File "/Users/laurent/.virtualenvs/proj/lib/python3.5/site-packages/behave_django/management/commands/behave.py", line 71, in Command
    option_list = BaseCommand.option_list + get_behave_options() + \
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

According to SO, `option_list` has been deprecated for a while and removed in Django 1.10,

http://stackoverflow.com/a/35181811/843194

Thanks!

**Comment by bittner** [comment] 2016-08-11 20:16
This is a duplicate of #2. Yes, we need to fix that. Contributions are welcome.

You can use Django 1.9 or even better Django 1.8 LTS, as long is this is not fixed.

**Closed by bittner** 2016-08-11 20:16 UTC
