### ISSUE TITLE
Django Timezone Change

### ISSUE THREAD

**Issue by rencesar** [behave/behave-django#35] opened 2017-04-15 04:55 UTC
Sometimes we need to use a timezone.now() in django for create models for exemple:
`default=timezone.now()`
And when We testing this module with time based tests, we have some problems to define this time. My propose is make a function with context to change a django's timezone.now for a timezone setted in context.date.

**Comment by bittner** [comment] 2017-06-20 21:37
I'm not sure whether using `timezone.now()` is actually a good idea in Django models. See [StackOverflow](https://stackoverflow.com/questions/2771676/django-datetime-issues-default-datetime-now) for a discussion.

Please give a concrete example what and how you would want to test your implementation. Give us some sample code (e.g. of how you would want to see things working). Then we can discuss things to find an appropriate solution.

**Comment by mixxorz** [comment] 2017-06-21 16:56
I actually don't think this belongs in behave-django. You might want to use something like [freezegun](https://github.com/spulec/freezegun) instead.

**Comment by bittner** [comment] 2017-06-23 15:48
Closing this issue as the problem is out of scope of this project. (It's not a problem of integrating behave and Django.)

Feel free to comment again and re-open the issue if you think we're wrong.

**Closed by bittner** 2017-06-23 15:48 UTC
Labels: invalid, wontfix
