### ISSUE TITLE
[docs] Allow to use custom test runner

### ISSUE THREAD

**Issue by andreyrusanov** [behave/behave-django#78] opened 2019-02-18 22:07 UTC
There are some cases where default test runners are not enough. It would be nice to add a Django settings for it.

**Comment by bittner** [comment] 2019-02-19 07:02
You can specify any custom test runner when you manually integrate Django and Behave [as described in the Behave docs](https://behave.readthedocs.io/en/latest/usecase_django.html#manual-integration). Is that sufficient for your use case?

**Comment by andreyrusanov** [comment] 2019-02-19 08:05
@bittner I am sorry I completely missed it.

**Comment by bittner** [comment] 2019-02-19 11:31
No problem. The information is maybe not super-easy to find (and there is no mention about this in the _behave-django_ docs). If you feel there is a better place for that information or we should mention it in this project's docs, please consider a pull request. Thank you!

**Comment by andreyrusanov** [comment] 2019-02-19 13:31
@bittner I think I was to hurry to resolve this issue. If you will take a look over here:
https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L136

you will see that test runner is selected from three possible test runners in any case (at lease to run setup test environment). 

I already implemented changes for it locally so perhaps I will open PR.

**Comment by bittner** [comment] 2020-06-08 12:26
The ultimate flexibility is implemented in the `behave` project itself via https://github.com/behave/behave/pull/795. It only needs to be merged. :roll_eyes: 

Yet still, this topic probably deserves being mentioned in our docs. If there's anyone who would want to attempt a related PR that would be great! :100:

**Comment by kingbuzzman** [comment] 2020-06-18 18:48
I could always resurrect behave/behave-django#100 , fix the outstanding comments, and add docs. Then make another PR that removes the code that you can merge when  behave/behave#795 gets merged in 2040 :D

**Comment by bittner** [comment] 2020-06-18 19:47
Very funny! No, seriously. There must be a better way.

We need to manage to convince @jenisys to make maintenance of the Behave project more sustainable. There must be more maintainers who take decisions if he's too busy to take care of merging not even _obviously useful_ enhancements.

**Comment by kingbuzzman** [comment] 2020-06-18 19:51
I thought that was you though. Don't you have merge access? You're a [Member]

**Comment by bittner** [comment] 2020-06-18 20:26
I can merge in this repository, yes. But the change belongs to the `behave` tool as such, not the Django integration. And I'm not a fan of workarounds. I'd rather fix the root cause.

**Comment by kingbuzzman** [comment] 2020-06-18 20:31
No what im saying is you're also a [Member] over at `behave/behave` also, you should be able to merge, now whether or not there might be a political issue with that is another story.

**Comment by bittner** [comment] 2020-06-18 21:18
I'm not. I'm an unprivileged member.

![image](https://user-images.githubusercontent.com/665072/85072742-de9b3080-b1b9-11ea-8847-bf8ea1ef6f8d.png)

Reads to me like, "Sorry, Peter, better luck next time!"

**Comment by bittner** [comment] 2021-07-07 19:07
behave/behave#795 is now merged. Related documentation is provided [in Behave's docs](https://behave.readthedocs.io/en/latest/behave.html#cmdoption-runner-class).

**Closed by bittner** 2021-07-07 19:07 UTC
Labels: help wanted, question
